// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://favhnurmqbtzttzxvfmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhdmhudXJtcWJ0enR0enh2Zm1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMjU0MzcsImV4cCI6MjA1NzYwMTQzN30.PvyTOGaeK7ID1D51SrwwDp2_N7mZzD1oIoEaSYN8NZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);